[editor]
line-number = "relative"
completion-timeout = 150
completion-trigger-len = 1
rulers = [100, 140]
color-modes = true
popup-border = "all"
bufferline = "always"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.auto-save]
focus-lost = true
after-delay.enable = false
after-delay.timeout = 2000

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "┆"
