theme = "seoul256-dark"

[editor]
scrolloff = 20
line-number = "relative"
cursorline = true
idle-timeout = 150
completion-timeout = 150
completion-trigger-len = 1
rulers = [100, 140]
bufferline = "always"
color-modes = true
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["version-control"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "total-line-numbers"]

[editor.lsp]
display-messages = true
display-progress-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.auto-save]
focus-lost = true
after-delay.enable = false
after-delay.timeout = 2000

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "┆"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

